### ISSUE TITLE
'Compile and restart' improvements - making sure it can happen when other things are borked

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/blacs#8]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/blacs/issues/8)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
If there's anything wrong with the connection table, or really, if there is really a any of a wide range of failures during startup, the GUI should still pop up, the error displayed somewhere and the user have the possibility of (and be direct to consider) opening the 'compile and restart' dialog.

This option should be available even if BLACS has serious problems initialising, because some of these problems can be due to mismatches between connection table and BLACS tab code. For example, today I modified the Novatech's `BLACS_connection` to include the serial baud rate.  I made it backward compatible (don't worry!), but before I did I had a connection table that didn't match what the BLACS tab expected. I couldn't start BLACS and I couldn't recompile the connection table except through runmanager. This has come up a lot in the wild if I understand correctly. So we need to just allow maximum breakage whilst still having the possibility of getting to that dialog.

Of course we should also do some basic checks for more obvious issues, like the connection table .py file doesn't exist (I think I want to copy a template to the given path in this case), or the h5 file doesn't exist (definitely want to bring up compile window in this case, probably with a message about 'do the first compile of this connection table').

We will also need the setting of what globals files to use to use in compilation to be available.

Is it much work to make `compile_and_restart` work standalone, but with an extra button to pop up the settings dialog for selecting globals? That button could be there even when the compile dialog is started normally from within BLACS - nothing wrong with having an extra way to get to the same dialog box.

I know it used to work standalone as a test. If we were to make it actually standalone we'd need it to know that it was standalone and not offer to restart BLACS (and look up the .py and .h5 files from labconfig, if it doesn't already do so).

Then we could add another shortcut to the labscript install folder, something like 'connection table compiler', that would just shortcut to `python -m blacs.compile_and_restart --compile-standalone` or something. We could direct users to use this to compile their connection table if things were broken.

In fact, if we'd rather not fix anything about BLACS startup, this alone would probably be satisfactory.

**Comment by jondoesntgit** [comment]
Hi Philip,

I currently borked my connections_table.h5 file. Is there a way to recompile it from the command line?

Jonathan

**Comment by jondoesntgit** [comment]
I have tried `python -m blacs.compile_and_restart --compile-standalone`. Python runs the command, but there is no connection_table.h5 update when I am done.

**Comment by chrisjbillington** [comment]
@jondoesntgit, that wasn't implemented, but generally speaking BLACS doesn't hard crash at startup anymore if the connection table is borked. Does the GUI show, and is the 'connection table' menu in the menu bar functional? If so, you ought to be able to select the option to recompile the connection table from there.

**Comment by jondoesntgit** [comment]
@chrisjbillington, thanks for responding!

The GUI never fully boots up. I tried renaming the connection_table.h5 that it was looking for to something like old_connection_table.h5. Now, when I try booting up BLACS, it gets stuck. I'll post my error log tomorrow.

**Comment by jondoesntgit** [comment]
I just tried re-installing blacs in another environment. When I boot up blacs from the command line, I get this error log in the GUI error screen. I never make it to the main gui.

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ls210809\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\ls210809\lib\site-packages\zprocess\utils.py", line 120, in _reraise
    raise value.with_traceback(traceback)
  File "C:\ProgramData\Anaconda3\envs\ls210809\lib\site-packages\labscript_utils\connections.py", line 46, in __init__
    with h5py.File(h5file,'r') as hdf5_file:
  File "C:\ProgramData\Anaconda3\envs\ls210809\lib\site-packages\labscript_utils\h5_lock.py", line 53, in __init__
    _File.__init__(self, name, mode, driver, libver, **kwds)
  File "C:\ProgramData\Anaconda3\envs\ls210809\lib\site-packages\h5py\_hl\files.py", line 442, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "C:\ProgramData\Anaconda3\envs\ls210809\lib\site-packages\h5py\_hl\files.py", line 195, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 96, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'C:\Experiments\example_apparatus\connection_table.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

```

**Comment by jondoesntgit** [comment]
If I open up the computer_name.ini file, and change apparatus_name to `apparatus_name = example_apparatus2`, the GUI now loads, but I still get the following pop-up window with the following error:

```Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ls210720\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\ls210720\lib\site-packages\zprocess\utils.py", line 120, in _reraise
    raise value.with_traceback(traceback)
  File "C:\ProgramData\Anaconda3\envs\ls210720\lib\site-packages\labscript_utils\connections.py", line 46, in __init__
    with h5py.File(h5file,'r') as hdf5_file:
  File "C:\ProgramData\Anaconda3\envs\ls210720\lib\site-packages\labscript_utils\h5_lock.py", line 53, in __init__
    _File.__init__(self, name, mode, driver, libver, **kwds)
  File "C:\ProgramData\Anaconda3\envs\ls210720\lib\site-packages\h5py\_hl\files.py", line 442, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "C:\ProgramData\Anaconda3\envs\ls210720\lib\site-packages\h5py\_hl\files.py", line 195, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 96, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'C:\Experiments\example_apparatus2\connection_table.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by jondoesntgit** [comment]
There is no "connections table" menu. Just File.

**Comment by dihm** [comment]
Jonathan,

Sorry I am very late to the party and probably won't be all that helpful.

I could be wrong, but I believe that while BLACS can launch with a borked `connection_table.h5`, it can't launch if the file just doesn't exist. Probably the simplest fix, assuming you have the ability, is to use runmanager to recompile your original `connection_table.py` (as if it were a normal shot) then copy the output to wherever the config.ini file wants it to be.

If that doesn't work, next step is to look at your config.ini file. What does it say for the following keys:

* Under [BLACS/plugins]: `connection_table`
* Under [paths]: `connection_table_h5` and `connection_table_py` 
* Under [DEFAULT]: `experiment_shot_storage` and 'labscriptlib` These two paths are used, under a default installation, in defining the connection table paths.

**Comment by jondoesntgit** [comment]
Thanks @dihm,

I ultimately got it working last week by deleting all of the labscript configuration folders, and running `labscript-profile-create`. After a little more tinkering after that, I was able to re-open BLACS, and get to the "Connections Table" menu.

If it gets borked again, I'll go through these steps.

Jonathan
