### ISSUE TITLE
Stop Order set to Start Order

### ISSUE THREAD

**Issue by zakv** [labscript-suite/blacs#84]
`QueueManager.manage()` has a copy/paste bug where it uses a device's value for `start_order` for both its `start_order` and `stop_order`. The string in the second line below should be `'stop_order'`.

https://github.com/labscript-suite/blacs/blob/0e153f233104dbaf0c7162cd37bfaa85fece64fd/blacs/experiment_queue.py#L600-L601

This is a simple one-line fix so I could issue a PR to resolve it.

**Comment by philipstarkey** [comment]
Sounds good!
